// Generated by rstantools.  Do not edit by hand.

/*
    useval is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    useval is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with useval.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0
#include <stan/model/model_header.hpp>
namespace model_mu_s2_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_mu_s2");
    reader.add_event(31, 29, "end", "model_mu_s2");
    return reader;
}
#include <stan_meta_header.hpp>
class model_mu_s2
  : public stan::model::model_base_crtp<model_mu_s2> {
private:
        int n;
        int m;
        std::vector<int> x;
        double mu_prior_mean;
        double mu_prior_sd;
        double s2_prior_a;
        double s2_prior_b;
public:
    model_mu_s2(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_mu_s2(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_mu_s2_namespace::model_mu_s2";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 3;
            context__.validate_dims("data initialization", "n", "int", context__.to_vec());
            n = int(0);
            vals_i__ = context__.vals_i("n");
            pos__ = 0;
            n = vals_i__[pos__++];
            check_greater_or_equal(function__, "n", n, 0);
            current_statement_begin__ = 4;
            context__.validate_dims("data initialization", "m", "int", context__.to_vec());
            m = int(0);
            vals_i__ = context__.vals_i("m");
            pos__ = 0;
            m = vals_i__[pos__++];
            check_greater_or_equal(function__, "m", m, 0);
            current_statement_begin__ = 5;
            validate_non_negative_index("x", "m", m);
            context__.validate_dims("data initialization", "x", "int", context__.to_vec(m));
            x = std::vector<int>(m, int(0));
            vals_i__ = context__.vals_i("x");
            pos__ = 0;
            size_t x_k_0_max__ = m;
            for (size_t k_0__ = 0; k_0__ < x_k_0_max__; ++k_0__) {
                x[k_0__] = vals_i__[pos__++];
            }
            size_t x_i_0_max__ = m;
            for (size_t i_0__ = 0; i_0__ < x_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "x[i_0__]", x[i_0__], 0);
            }
            current_statement_begin__ = 8;
            context__.validate_dims("data initialization", "mu_prior_mean", "double", context__.to_vec());
            mu_prior_mean = double(0);
            vals_r__ = context__.vals_r("mu_prior_mean");
            pos__ = 0;
            mu_prior_mean = vals_r__[pos__++];
            current_statement_begin__ = 9;
            context__.validate_dims("data initialization", "mu_prior_sd", "double", context__.to_vec());
            mu_prior_sd = double(0);
            vals_r__ = context__.vals_r("mu_prior_sd");
            pos__ = 0;
            mu_prior_sd = vals_r__[pos__++];
            check_greater_or_equal(function__, "mu_prior_sd", mu_prior_sd, 0);
            current_statement_begin__ = 10;
            context__.validate_dims("data initialization", "s2_prior_a", "double", context__.to_vec());
            s2_prior_a = double(0);
            vals_r__ = context__.vals_r("s2_prior_a");
            pos__ = 0;
            s2_prior_a = vals_r__[pos__++];
            check_greater_or_equal(function__, "s2_prior_a", s2_prior_a, 0);
            current_statement_begin__ = 11;
            context__.validate_dims("data initialization", "s2_prior_b", "double", context__.to_vec());
            s2_prior_b = double(0);
            vals_r__ = context__.vals_r("s2_prior_b");
            pos__ = 0;
            s2_prior_b = vals_r__[pos__++];
            check_greater_or_equal(function__, "s2_prior_b", s2_prior_b, 0);
            // initialize transformed data variables
            // execute transformed data statements
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 15;
            num_params_r__ += 1;
            current_statement_begin__ = 16;
            num_params_r__ += 1;
            current_statement_begin__ = 17;
            validate_non_negative_index("logit_p", "m", m);
            num_params_r__ += (1 * m);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_mu_s2() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 15;
        if (!(context__.contains_r("mu")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable mu missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("mu");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "mu", "double", context__.to_vec());
        double mu(0);
        mu = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(mu);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable mu: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 16;
        if (!(context__.contains_r("s2")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable s2 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("s2");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "s2", "double", context__.to_vec());
        double s2(0);
        s2 = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, s2);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable s2: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 17;
        if (!(context__.contains_r("logit_p")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable logit_p missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("logit_p");
        pos__ = 0U;
        validate_non_negative_index("logit_p", "m", m);
        context__.validate_dims("parameter initialization", "logit_p", "double", context__.to_vec(m));
        std::vector<double> logit_p(m, double(0));
        size_t logit_p_k_0_max__ = m;
        for (size_t k_0__ = 0; k_0__ < logit_p_k_0_max__; ++k_0__) {
            logit_p[k_0__] = vals_r__[pos__++];
        }
        size_t logit_p_i_0_max__ = m;
        for (size_t i_0__ = 0; i_0__ < logit_p_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_unconstrain(logit_p[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable logit_p: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 15;
            local_scalar_t__ mu;
            (void) mu;  // dummy to suppress unused var warning
            if (jacobian__)
                mu = in__.scalar_constrain(lp__);
            else
                mu = in__.scalar_constrain();
            current_statement_begin__ = 16;
            local_scalar_t__ s2;
            (void) s2;  // dummy to suppress unused var warning
            if (jacobian__)
                s2 = in__.scalar_lb_constrain(0, lp__);
            else
                s2 = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 17;
            std::vector<local_scalar_t__> logit_p;
            size_t logit_p_d_0_max__ = m;
            logit_p.reserve(logit_p_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < logit_p_d_0_max__; ++d_0__) {
                if (jacobian__)
                    logit_p.push_back(in__.scalar_constrain(lp__));
                else
                    logit_p.push_back(in__.scalar_constrain());
            }
            // model body
            current_statement_begin__ = 23;
            lp_accum__.add(normal_log(mu, mu_prior_mean, mu_prior_sd));
            current_statement_begin__ = 24;
            lp_accum__.add(inv_gamma_log(s2, s2_prior_a, s2_prior_b));
            current_statement_begin__ = 25;
            for (int j = 1; j <= m; ++j) {
                current_statement_begin__ = 26;
                lp_accum__.add(normal_log(get_base1(logit_p, j, "logit_p", 1), mu, stan::math::sqrt(s2)));
                current_statement_begin__ = 27;
                lp_accum__.add(binomial_log(get_base1(x, j, "x", 1), n, inv_logit(get_base1(logit_p, j, "logit_p", 1))));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("mu");
        names__.push_back("s2");
        names__.push_back("logit_p");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(m);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_mu_s2_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        double mu = in__.scalar_constrain();
        vars__.push_back(mu);
        double s2 = in__.scalar_lb_constrain(0);
        vars__.push_back(s2);
        std::vector<double> logit_p;
        size_t logit_p_d_0_max__ = m;
        logit_p.reserve(logit_p_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < logit_p_d_0_max__; ++d_0__) {
            logit_p.push_back(in__.scalar_constrain());
        }
        size_t logit_p_k_0_max__ = m;
        for (size_t k_0__ = 0; k_0__ < logit_p_k_0_max__; ++k_0__) {
            vars__.push_back(logit_p[k_0__]);
        }
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            if (!include_gqs__ && !include_tparams__) return;
            if (!include_gqs__) return;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    std::string model_name() const {
        return "model_mu_s2";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "s2";
        param_names__.push_back(param_name_stream__.str());
        size_t logit_p_k_0_max__ = m;
        for (size_t k_0__ = 0; k_0__ < logit_p_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "logit_p" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
        }
        if (!include_gqs__) return;
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "s2";
        param_names__.push_back(param_name_stream__.str());
        size_t logit_p_k_0_max__ = m;
        for (size_t k_0__ = 0; k_0__ < logit_p_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "logit_p" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
        }
        if (!include_gqs__) return;
    }
}; // model
}  // namespace
typedef model_mu_s2_namespace::model_mu_s2 stan_model;
#ifndef USING_R
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
#endif
#endif
